name: Capture Kids Today

on:
  schedule:
    # JST(UTC+9) の 06:00〜22:00 を30分間隔で（UTCだと 21-13時）
    - cron: "*/30 21-23,0-13 * * *"
  workflow_dispatch: {}  # 手動実行ボタン

permissions:
  contents: write

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho fonts-noto-cjk

      - name: Install deps
        run: |
          npm init -y
          npm install puppeteer

      - name: Ensure output dir
        run: mkdir -p shots scripts

      - name: Run capture script
        run: node scripts/capture-kids.mjs

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add shots/kids-today.png
          git commit -m "auto: capture kids today" || echo "no changes"
          git push
