name: Capture Kids Today

on:
  schedule:
    - cron: "*/30 21-23,0-13 * * *" # JST 06:00-22:00 を30分ごと
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo tree
        run: |
          pwd
          ls -la
          echo "---- scripts"; ls -la scripts || true
          echo "---- shots";   ls -la shots || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho fonts-noto-cjk

      - name: Install deps (puppeteer)
        run: |
          npm init -y
          npm install puppeteer

      - name: Ensure dirs
        run: |
          mkdir -p shots

      # ★ スクリプトを“その場で”実行（ファイル作成不要）
      - name: Run capture inline
        shell: bash
        run: |
          node - <<'NODE'
          import puppeteer from "puppeteer";
          const URL = "https://kids.yahoo.co.jp/today";
          const OUT = "shots/kids-today.png";
          const VIEWPORT = { width: 1920, height: 1080 };
          (async () => {
            const browser = await puppeteer.launch({
              headless: "new",
              args: ["--no-sandbox","--disable-setuid-sandbox","--lang=ja-JP,ja"],
              defaultViewport: VIEWPORT,
            });
            const page = await browser.newPage();
            await page.setExtraHTTPHeaders({ "Accept-Language": "ja-JP,ja;q=0.9" });
            await page.setUserAgent(
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) " +
              "AppleWebKit/537.36 (KHTML, like Gecko) " +
              "Chrome/126.0.0.0 Safari/537.36"
            );
            await page.goto(URL, { waitUntil: "networkidle2", timeout: 120000 });
            // 画面全体スクショ（必要なら要素指定に変更可）
            await page.screenshot({ path: OUT, type: "png" });
            await browser.close();
            console.log(`Saved: ${OUT}`);
          })();
          NODE

      - name: Commit & push image
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add shots/kids-today.png
          git commit -m "auto: capture kids today" || echo "no changes"
          git push
