name: Capture Kids Yahoo Today

on:
  workflow_dispatch: {}
  # 毎日定期実行したい場合（JST 06:00 = UTC 21:00）
  # schedule:
  #   - cron: "0 21 * * *"

permissions:
  contents: write

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho fonts-noto-cjk

      - name: Install dependencies (puppeteer)
        run: |
          npm init -y
          npm install puppeteer

      - name: Ensure output dir
        run: mkdir -p shots

      # 実ファイルの先頭表示＋ $x 検出
      - name: Sanity check script ($x detector & show head)
        run: |
          echo "=== list scripts ==="
          ls -la scripts || true
          echo "=== head of scripts/capture-kids.mjs ==="
          sed -n '1,120p' scripts/capture-kids.mjs || { echo "scripts/capture-kids.mjs not found"; exit 1; }
          echo "=== grep for \$x ==="
          if grep -n '\$x(' scripts/capture-kids.mjs; then
            echo 'NG: $x is still used in scripts/capture-kids.mjs'
            exit 2
          else
            echo 'OK: no $x usage'
          fi

      - name: Run capture script
        run: node scripts/capture-kids.mjs

      - name: Commit & Push outputs (and script if updated)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add shots/*.png scripts/capture-kids.mjs || true
          git commit -m "Update kids-today capture (and script if changed) [skip ci]" || echo "No changes to commit"
          git pull --rebase origin "${GITHUB_REF_NAME:-main}"
          git push origin HEAD:"${GITHUB_REF_NAME:-main}"
