name: Capture Kids Yahoo Today

on:
  schedule:
    # 毎日00:00 JST（GitHubはUTCなので9時間引いた 15:00 UTC）
    - cron: "0 15 * * *"
  workflow_dispatch:       # 手動実行も可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install puppeteer
      
    - name: Show script head (sanity check)
      run: |
        echo "==== show first 120 lines ===="
        sed -n '1,120p' scripts/capture-kids.mjs | sed 's/\t/    /g'
        echo "==== grep for $x usage ===="
        if grep -n '\$x(' scripts/capture-kids.mjs; then
          echo 'ERROR: page.$x still exists in the file' && exit 1
        else
          echo 'OK: no $x usage'
        fi

    - name: Run capture script
      run: node scripts/capture-kids.mjs

    - name: Commit & Push
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add shots/*.png
        git commit -m "Update kids today screenshot [skip ci]" || echo "No changes to commit"
        git pull --rebase origin main
        git push origin main
