name: Capture Kids Yahoo Today

on:
  workflow_dispatch:
  schedule:
    - cron: '5 21 * * *'   # JST 06:05

permissions:
  contents: write

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk

      - name: Init minimal project and install puppeteer
        run: |
          if [ ! -f package.json ]; then echo '{}' > package.json; fi
          npm pkg set type="module"
          npm i puppeteer@22

      - name: Ensure output dirs
        run: |
          mkdir -p shots
          mkdir -p scripts

      # ---- capture script を Python で生成（main フォールバックなし）----
      - name: Generate capture script
        shell: bash
        run: |
          python3 - <<'PY'
          import os, textwrap, pathlib
          pathlib.Path("scripts").mkdir(parents=True, exist_ok=True)
          js = textwrap.dedent(r"""
            // SIGNATURE: kids-today v3 NO_MAIN_FALLBACK
            import fs from "node:fs";
            import puppeteer from "puppeteer";

            const URL  = "https://kids.yahoo.co.jp/today";
            const OUT  = "shots/kids-today.png";
            const VIEW = { width: 1920, height: 1080 };

            const CANDIDATES = [
              '#__next > div > main > div[class^="Today_info__"]',
              '#__next main div[class^="Today_info__"]',
              '#__next main div[class*="Today_info__"]',
              '#__next main section[class^="Today_info__"]',
              '#__next main section[class*="Today_info__"]'
            ];

            function ensureDirFor(p){
              const d = p.split("/").slice(0,-1).join("/");
              if (d && !fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
            }

            async function waitAndPick(page){
              await page.waitForSelector("main", { timeout: 15000 }).catch(()=>{});
              for (const sel of CANDIDATES){
                try{
                  await page.waitForSelector(sel, { timeout: 4000 });
                  const el = await page.$(sel);
                  if (el) return { el, sel };
                }catch{}
              }
              return { el:null, sel:null };
            }

            (async ()=>{
              console.log("SCRIPT_SIGNATURE: kids-today v3 NO_MAIN_FALLBACK");
              ensureDirFor(OUT);

              const browser = await puppeteer.launch({
                headless: "new",
                args: ["--no-sandbox", "--disable-setuid-sandbox", "--lang=ja-JP,ja"],
                defaultViewport: VIEW
              });

              try{
                const page = await browser.newPage();
                await page.setExtraHTTPHeaders({ "Accept-Language": "ja-JP,ja;q=0.9" });
                await page.setUserAgent(
                  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) " +
                  "AppleWebKit/537.36 (KHTML, like Gecko) " +
                  "Chrome/126.0.0.0 Safari/537.36"
                );

                // 軽量化（不要なら削除可）
                await page.setRequestInterception(true);
                page.on("request", req => {
                  const t = req.resourceType();
                  if (t === "image" || t === "font" || t === "media") req.abort();
                  else req.continue();
                });

                await page.goto(URL, { waitUntil: "networkidle2", timeout: 120000 });

                const { el, sel } = await waitAndPick(page);
                if (!el){
                  console.error("Target selector not found. (NO fallback to 'main')");
                  process.exitCode = 2;
                  return;
                }

                await el.screenshot({ path: OUT });
                console.log("Captured by selector:", sel);
                console.log("Saved:", OUT);
              }catch(e){
                console.error("Capture failed:", e);
                process.exitCode = 1;
              }finally{
                await browser.close();
              }
            })();
          """).strip() + "\n"
          open("scripts/capture-kids.mjs", "w", encoding="utf-8").write(js)
          echo_head = "\n".join(js.splitlines()[:24])
          print("=== head of scripts/capture-kids.mjs ===")
          print(echo_head)
          PY

      # ここが YAML 構文エラーになりやすい部分。必ずダブルクォートで囲む！
      - name: "Guard - script must NOT contain: Captured by selector: main"
        shell: bash
        run: |
          set -e
          test -f scripts/capture-kids.mjs
          if grep -q "Captured by selector: main" scripts/capture-kids.mjs; then
            echo "Found forbidden fallback to 'main' in the script."
            exit 1
          fi

      - name: Run capture script
        run: node scripts/capture-kids.mjs

            # 生成結果（shots/kids-today.png）をコミット＆プッシュ
            # 生成された画像（shots/kids-today.png）だけをコミット＆プッシュ
            
      - name: Commit & Push output (hard-sync)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          echo "=== Hard-sync commit step ==="

          # 1) 生成した画像を一時退避
          cp -f shots/kids-today.png /tmp/kids-today.png

          # 2) リポジトリをリモートの最新に強制同期（作業ツリーを一度クリーンに）
          git fetch origin "$BRANCH"
          # Actions は detached HEAD なので、そのまま origin/BRANCH に合わせる
          git reset --hard "origin/$BRANCH"
          git clean -fdx

          # 3) 画像を復元
          mkdir -p shots
          cp -f /tmp/kids-today.png shots/kids-today.png

          # 4) 画像だけステージ & コミット & プッシュ
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f shots/kids-today.png || true

          # 変更がなければ終了
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update kids-today capture [skip ci]"
          git push origin HEAD:"$BRANCH"
