name: Capture Kids Yahoo Today

on:
  workflow_dispatch: {}     # 手動実行のみ（慣れるまでおすすめ）
  # schedule:
  #   - cron: "0 15 * * *"  # JST 00:00（= UTC 15:00）に毎日回す場合

permissions:
  contents: write

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho fonts-noto-cjk

      - name: Install puppeteer
        run: |
          npm init -y
          npm install puppeteer

      - name: Ensure output dir
        run: mkdir -p shots

      # ★ここが Sanity check（Run capture script の直前に置く）
      - name: Sanity check script ($x detector)
        run: |
          echo "==== working dir ====" && pwd
          echo "==== list scripts dir ====" && (ls -la scripts || true)
          echo "==== head of script ===="
          sed -n '1,120p' scripts/capture-kids.mjs || { echo "File not found"; exit 1; }
          echo "==== grep $x ===="
          if grep -n '\$x(' scripts/capture-kids.mjs; then
            echo 'ERROR: $x still exists in scripts/capture-kids.mjs'
            exit 1
          else
            echo 'OK: no $x usage'
          fi

      - name: Run capture script
        run: node scripts/capture-kids.mjs

      - name: Commit & Push image
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add shots/*.png
          git commit -m "Update kids today screenshot [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
