name: Capture Kids Yahoo Today

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 0 * * *"   # 任意（毎日 09:05 JST）

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリ取得（履歴が必要なので fetch-depth:0）
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 2) Node を用意
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) 日本語フォント（puppeteer の描画が豆腐にならないように）
      - name: Install Japanese fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont-gothic fonts-ipafont-mincho

      # 4) 最小の npm 環境 + puppeteer をインストール
      - name: Init minimal project and install puppeteer
        run: |
          set -e
          echo '{}' > package.json
          npm i puppeteer@22

      # 5) 出力フォルダ
      - name: Ensure output dirs
        run: |
          mkdir -p shots scripts

      # 6) キャプチャスクリプトを生成（自動生成）
      - name: Generate capture script
        run: |
          cat > scripts/capture-kids.mjs <<'JS'
          // Kids Yahoo!「今日は何の日」 指定セレクタを優先して要素キャプチャ
          import fs from "node:fs";
          import puppeteer from "puppeteer";

          const URL  = "https://kids.yahoo.co.jp/today";
          const OUT  = "shots/kids-today.png";
          const VIEW = { width: 1920, height: 1080 };

          const CANDIDATES = [
            '#__next > div > main > div[class^="Today_info__"]',
            '#__next main [class^="Today_info__"]',
            'main .Today_info',                    // 念のため
            'main'                                 // 最後のフォールバック（満たさない時のみ）
          ];

          function ensureDir(p){
            const d = p.split("/").slice(0,-1).join("/");
            if (d && !fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
          }

          (async () => {
            ensureDir(OUT);

            const browser = await puppeteer.launch({
              headless: "new",
              args: ["--no-sandbox", "--disable-setuid-sandbox", "--lang=ja-JP,ja"],
              defaultViewport: VIEW
            });

            try {
              const page = await browser.newPage();
              await page.setExtraHTTPHeaders({ "Accept-Language": "ja-JP,ja;q=0.9" });
              await page.setUserAgent(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) " +
                "AppleWebKit/537.36 (KHTML, like Gecko) " +
                "Chrome/126.0.0.0 Safari/537.36"
              );

              await page.goto(URL, { waitUntil: "networkidle2", timeout: 120000 });

              // ローディング待ち（静的に main が生えない場合があるため少し待つ）
              await page.waitForSelector("main", { timeout: 8000 }).catch(() => {});

              let captured = false;
              for (const sel of CANDIDATES) {
                const el = await page.$(sel);
                if (el) {
                  await el.screenshot({ path: OUT });
                  console.log("Captured by selector:", sel);
                  captured = true;
                  break;
                }
              }

              if (!captured) {
                console.warn("Fallback to full page capture.");
                await page.screenshot({ path: OUT, fullPage: true });
              }

              console.log("Saved:", OUT);
              console.log("SCRIPT_SIGNATURE: kids-today v4 HARD_SYNC");
            } catch (e) {
              console.error(e);
              process.exitCode = 1;
            } finally {
              await browser.close();
            }
          })();
          JS

      # 7) 実行
      - name: Run capture script
        run: node scripts/capture-kids.mjs

      # 8) 生成画像だけを安全にコミット＆プッシュ（ハードリセット方式）
      - name: Commit & Push output (hard-sync)
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          set -e
          echo "=== Hard-sync commit step ==="
          cp -f shots/kids-today.png /tmp/kids-today.png

          git fetch origin "$BRANCH"
          git reset --hard "origin/$BRANCH"
          git clean -fdx

          mkdir -p shots
          cp -f /tmp/kids-today.png shots/kids-today.png

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -f shots/kids-today.png

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update kids-today capture [skip ci]"
          git push origin HEAD:"$BRANCH"
