name: Fetch Open-Meteo JSON

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install (none)

      - name: Run fetch script
        run: node scripts/fetch-openmeteo.js

      - name: Pull (rebase) then push with retry
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 変更がなければ何もしない
          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi

          git add data/*.json
          git commit -m "chore(data): update open-meteo JSON [skip ci]"

          # 競合を避けるためrebase pull→push（2回まで再試行）
          for i in 1 2; do
            if git pull --rebase origin main; then
              if git push origin HEAD:main; then
                echo "Pushed."
                exit 0
              fi
            fi
            echo "Retry $i ..."
            sleep 3
          done

          echo "Push failed"; exit 1
