name: Fetch Open-Meteo JSON

on:
  schedule:
    - cron: "*/15 * * * *"    # 15分ごと
  workflow_dispatch:

# 同時実行を止めて衝突回避
concurrency:
  group: fetch-openmeteo-json
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # ★ ここがポイント：常に最新のremote/mainに合わせる
      - name: Sync to latest remote (hard reset)
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}}"
          git fetch origin "$BRANCH"
          git reset --hard "origin/$BRANCH"

      - name: Generate JSON
        run: node scripts/fetch-openmeteo.js

      - name: Commit if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git diff --cached --quiet && echo "No changes to commit." && exit 0
          git commit -m "chore(data): update open-meteo JSON [skip ci]"

      # ★ push がはじかれたら、もう一度同期→再生成→push
      - name: Push with one retry after re-sync
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}}"
          set +e
          git push origin "HEAD:$BRANCH"
          if [ $? -ne 0 ]; then
            echo "Push rejected, re-sync + regenerate + push again..."
            git fetch origin "$BRANCH"
            git reset --hard "origin/$BRANCH"
            node scripts/fetch-openmeteo.js
            git add data/*.json || true
            git diff --cached --quiet && echo "No changes to commit after retry." && exit 0
            git commit -m "chore(data): update open-meteo JSON [skip ci]"
            git push origin "HEAD:$BRANCH"
          fi
