name: Fetch Open-Meteo JSON
on:
  schedule: [ { cron: "*/15 * * * *" } ]   # 15分ごと
  workflow_dispatch:
permissions:
  contents: write                           # ← これが超重要（コミット権限）
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22" }
      - name: Fetch Open-Meteo and write JSONs
        run: node scripts/fetch-openmeteo.js
      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "chore(data): update open-meteo JSON [skip ci]" || echo "nothing to commit"
          git push
